global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "multimodal-api"
    scrape_interval: 5s
    scrape_timeout: 4s
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8000"]
